### ISSUE TITLE
Currently used edge.js is incompatible w/ node v14.x

### ISSUE THREAD

**Issue by austincondict-AngelOak** [skmp/node-msoffice-pdf#14]
```
Welcome to Node.js v14.15.4.      
Type ".help" for more information.
> let msopdf = require('node-msoffice-pdf');
Uncaught:
Error: The edge module has not been pre-compiled for node.js version v14.15.4. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (C:\Users\ACondict\Development\AOCA-PurchasedDocDump\node_modules\edge\lib\edge.js:20:11)
    at Object.<anonymous> (C:\Users\ACondict\Development\AOCA-PurchasedDocDump\node_modules\edge\lib\edge.js:32:102)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
>
```

**Comment by fercslv** [comment]
You need node-gyp installed so you can build the lib.

Install node-gyp by doing the following command:
`npm install -g node-gyp`

After you installed this dependency go into Edge or Edge-js folder (inside node_modules of your project folder). Execute the next command then:
`node-gyp build`
