### ISSUE TITLE
Error: The edge native module is not available

### ISSUE THREAD

**Issue by protzi** [skmp/node-msoffice-pdf#6]
when try to lunch app after installing, get this error

/home/user/Desktop/test-app/pdf/node_modules/edge/lib/edge.js:36
    throw new Error('The edge native module is not available at ' + builtEdge 
    ^

Error: The edge native module is not available at /home/user/Desktop/test-app/pdf/node_modules/edge/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge
    at Object.<anonymous> (/home/user/Desktop/test-app/pdf/node_modules/edge/lib/edge.js:36:11)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/home/user/Desktop/test-app/pdf/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/Desktop/test-app/pdf/node_modules/node-msoffice-pdf/lib.js:1:74)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js](/home/protz/Desktop/test-app/pdf/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by skmp** [comment]
As per the readme, this only works for Windows
